LASAGNE-Open-Systems/LASAGNE-Core

- README.md
Added information for getting started, contributions and licensing.
> Updated readme markdown

- LDBC/LDBC.mwc
- TAF/taf/Version.h
- docs/html/documentation/android_notes.html
- docs/html/documentation/linux_notes.html
- docs/html/documentation/windows_notes.html
Fixed an MPC generation issue, looking for ODBC which isn't present.
Fixed the TAF version to update to 1.4.3
> Fixes for Release/1.4.3

- daf/OS.cpp
- daf/OS.h
This function may be expanded to translate more windows only errors to errno in future as required
> Added local DAF_OS implementation of last_error() that translates some windows errors

- daf/OS.h
Use > operator for comaprisons
> DAF_OS use magnitude > operator

- TAF/TAFServer/TAFServer.cpp
- TAF/dds/DDSDefs.h
- TAF/dds/DDSQos.h
- TAF/taf/ORBManager.h
- TAF/taf/extensions/TAFExtensions.h
- daf/Config.h
Changing this has a minor dependency ripple change through the core.
> Rename DAF_UNUSED_ARG to DAF_UNUSED_STATIC to better reflect its usage

- TAF/training/CORBActiveService/CORBActiveService.cpp
- TAF/training/DDSActiveService/DDSActiveService.cpp
minor change to training examples from course feedback
> Incorporate change recommended in training to use topic assignment

- .gitattributes
Ignoring sqlite3 as vendored code
Ignoring docs as documentation
> Setting git attributes

- TAF/TAFServer/TAFServer.mpc
- TAF/examples/CORBAExample/CORBAExample.mpc
- TAF/examples/TextParser/TextParser.mpc
- TAF/tests/TAFServerLoader/TAFServerLoader.mpc
- tests/ARGVTest/ARGVTest.mpc
- tests/ServiceConfiguratorTest/ServiceConfiguratorTest.mpc
- tests/TaskExecutorTest/TaskExecutorTest.mpc
Also removed argument setting option for those below vc14
> Updated mpc's to support debug args in vs2017.

- LDBC/SQLite/sqlite3/shell.c
- LDBC/SQLite/sqlite3/sqlite3.h
- LDBC/SQLite/sqlite3/sqlite3ext.h
Also removed argument setting option for those below vc14
> Update sqlite3 api to latest 3.19.2 for LDBCSqlite

- TAF/training/CORBActiveService/CORBActiveDataSupport.h
- TAF/training/DDSActiveService/DDSActiveDataSupport.h
> Typo caused warning on GCC 6.2

- docs/html/documentation/linux_notes.html
Lib directories were being added to the general PATH for no reason on Linux.
> Linux documentation fix for path

- VERSION
Adding a version file to address issue #16
> Added version file

- README.md
- VERSION
Added information about test compiler configurations and build dependency versions to the VERSION file and README.md
> Improving version information

- NEWS.md
The changelog has been added as a NEW.md file. The markdown makes the formatting nicer for readers on GitHub.
Addresses issue #77
> Added a changelog

- MPC/config/opendds.mpb
- TAF/training/DDSActiveService/ODDSActiveService.mpb
Tweaked JAVA support to fix missing include (DDSActiveService now can create java bindings for topic).
> Fixed support for Selective Java bindings and add missing include path

- .travis.yml
- NEWS.md
- README.md
- TAF/taf/Version.h
- VERSION
- appveyor.yml
- daf/Version.h
- docs/lasagne-core.doxyfile
Updated references to version numbering
Updated dependency information
Updated the changelog
> Release 1.4.4 checklist

- TAF/TAFSecurity/TAFSecurityLoader.cpp
- TAF/TAFSecurity/TAFSecurityLoader.h
- TAF/taf/ORBManager.cpp
- TAF/taf/PropertyLoader.cpp
- bin/LASAGNEProperties.conf
- daf/Constants.h
Updated default properties to include TAFSecurity properties
> Use positive logic to enable Security when it is included in the build

- NEWS.md
- TAF/taf/Version.h
- VERSION
- daf/Version.h
- docs/lasagne-core.doxyfile
- Updated references to version numbering
- Updated references to dependency versions and compiler support
- Updated the changelog in NEWS.md
> Release 1.5 checklist

- README.md
> Upgraded ACE/TAO to latest micro

- NEWS.md
- VERSION
Fixed additional ACE-TAO references following the pull request from @jwillemsen
> Updated references to ACE-TAO 6.4.4

- README.md
- VERSION
> Upgrade ACE/TAO to x.4.5 and OpenDDS to 3.12
